name: Benchmark on Emulator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4,10,18 * * *"

jobs:
  benchmark-android:
    strategy:
      fail-fast: false
      matrix:
        instrument-args:
          - "-e class com.google.samples.apps.nowinandroid.startup.StartupBenchmark#startupPrecompiledWithBaselineProfile"
          - "-e class com.google.samples.apps.nowinandroid.foryou.ScrollForYouFeedBenchmark#scrollFeedCompilationBaselineProfile"
          - "-e class com.google.samples.apps.nowinandroid.foryou.ScrollForYouFeedBenchmark#scrollFeedCompilationMemoryMaxBaselineProfile"
    uses: Frozen-Bytes/actions/.github/workflows/android-macrobenchmark-gradle.yml@main
    with:
      api-level: 30
      target: google_apis
      arch: x86_64
      force-avd-creation: true
      emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -memory 4096
      disable-animations: true
      gradle-cache-readonly: false
      instrument-args: ${{ matrix.instrument-args }}
