name: Benchmark on Emulator (Blacksmith)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "15 * * * *"

jobs:
  benchmark-android:
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - name: startup
            args: "-e class com.google.samples.apps.nowinandroid.startup.StartupBenchmark#startupPrecompiledWithBaselineProfile"
          - name: scrollforyou-frametime
            args: "-e class com.google.samples.apps.nowinandroid.foryou.ScrollForYouFeedBenchmark#scrollFeedCompilationBaselineProfile"
          - name: scrollforyou-memory-max
            args: "-e class com.google.samples.apps.nowinandroid.foryou.ScrollForYouFeedBenchmark#scrollFeedCompilationMemoryMaxBaselineProfile"
    name: ${{ matrix.benchmark.name }}
    uses:  fbtester1/nowinandroid/.github/workflows/android-macrobenchmark-gradle-blacksmith.yml@main
    with:
      api-level: 34
      target: google_apis
      arch: x86_64
      force-avd-creation: true
      emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -memory 8192 -cores 4
      disable-animations: true
      gradle-cache-readonly: false
      instrument-args: ${{ matrix.benchmark.args }}
      runs: 10
      args: "--verbose --all-methods --all-measures --aggregate median"
      artifact-name: "benhcomp-${{ matrix.benchmark.name }}.json"
      artifact-macrobenchmark-name: "${{ matrix.benchmark.name }}-raw-macrobenchmark"
